version: "3"

services:
  node_basic:
    build:
      context: node-server
    ports:
      - 3000:3000
    working_dir: /usr/src/app

  nginx:
    image: nginx
    ports:
      - "443:443"
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./nginx-server/proxy.conf:/etc/nginx/conf.d/default.conf
      # - ./certs/server.crt:/etc/ssl/server.crt
      # - ./certs/server.key:/etc/ssl/server.key
      - ./certs-true/server.crt:/etc/ssl/server.crt
      - ./certs-true/server.key:/etc/ssl/server.key
      - ./certs-true/dhparams.pem:/etc/nginx/client_certs/dhparams.pem
      - ./certs-true/ca.crt:/etc/nginx/client_certs/ca.crt
